project_id = "kskpmgohvrljbdphyzkw"

[functions.nbs-exchange-rate]
verify_jwt = true

[functions.apr-lookup]
verify_jwt = false

[functions.sef-send-invoice]
verify_jwt = true

[functions.sef-fetch-invoices]
verify_jwt = true

[functions.delete-user]
verify_jwt = false

[functions.sef-fetch-purchase-invoices]
verify_jwt = true

[functions.sef-fetch-sales-invoices]
verify_jwt = true

[functions.sef-get-invoice-xml]
verify_jwt = true

[functions.sef-accept-reject-invoice]
verify_jwt = true

[functions.sef-cancel-sales-invoice]
verify_jwt = true

[functions.sef-enrich-invoices]
verify_jwt = true

[functions.sef-background-sync]
verify_jwt = false

[functions.sef-long-sync]
verify_jwt = false

[functions.sef-continue-sync]
verify_jwt = false

[functions.parse-pausalni-pdf]
verify_jwt = true
